### ISSUE TITLE
Windows sub millisecond resolution

### ISSUE THREAD

**Issue by tenox7** [digineo/go-ping#11]
When running on Windows and pinging targets on LAN with sub millisecond rtt, go-ping displays only 0.

```
C:\>ping-monitor -pingInterval 1s -reportInterval 1s 192.168.1.1
192.168.1.1: {PacketsSent:1 PacketsLost:0 Best:0 Worst:0 Median:0 Mean:0 StdDev:0}
192.168.1.1: {PacketsSent:1 PacketsLost:0 Best:0 Worst:0 Median:0 Mean:0 StdDev:0}
192.168.1.1: {PacketsSent:1 PacketsLost:0 Best:0 Worst:0 Median:0 Mean:0 StdDev:0}
192.168.1.1: {PacketsSent:1 PacketsLost:0 Best:0 Worst:0 Median:0 Mean:0 StdDev:0}
192.168.1.1: {PacketsSent:1 PacketsLost:0 Best:0 Worst:0 Median:0 Mean:0 StdDev:0}
192.168.1.1: {PacketsSent:1 PacketsLost:0 Best:0 Worst:0 Median:0 Mean:0 StdDev:0}
```

When equivalent is run on Linux or WSL, correct numbers are shows:

```
# ping-monitor -pingInterval 1s -reportInterval 1s 192.168.1.1
192.168.1.1: {PacketsSent:1 PacketsLost:0 Best:0.5619 Worst:0.5619 Median:0.5619 Mean:0.5619 StdDev:0}
192.168.1.1: {PacketsSent:1 PacketsLost:0 Best:0.6725 Worst:0.6725 Median:0.6725 Mean:0.6725 StdDev:0}
192.168.1.1: {PacketsSent:1 PacketsLost:0 Best:0.6144 Worst:0.6144 Median:0.6144 Mean:0.6144 StdDev:0}
192.168.1.1: {PacketsSent:1 PacketsLost:0 Best:0.4926 Worst:0.4926 Median:0.4926 Mean:0.4926 StdDev:0}
192.168.1.1: {PacketsSent:1 PacketsLost:0 Best:0.4771 Worst:0.4771 Median:0.4771 Mean:0.4771 StdDev:0}
```

If RTT is above 1ms then no problem is observed.

**Comment by corny** [comment]
As you describe, this issue is related to windows. On Linux I get:
```
# ping-monitor -pingInterval 1s -reportInterval 1s 127.0.0.1
127.0.0.1: {PacketsSent:1 PacketsLost:0 Best:0.162971 Worst:0.162971 Median:0.162971 Mean:0.162971 StdDev:0}
127.0.0.1: {PacketsSent:1 PacketsLost:0 Best:0.180671 Worst:0.180671 Median:0.180671 Mean:0.180671 StdDev:0}
127.0.0.1: {PacketsSent:1 PacketsLost:0 Best:0.223151 Worst:0.223151 Median:0.223151 Mean:0.223151 StdDev:0}
127.0.0.1: {PacketsSent:1 PacketsLost:0 Best:0.118226 Worst:0.118226 Median:0.118226 Mean:0.118226 StdDev:0}
127.0.0.1: {PacketsSent:1 PacketsLost:0 Best:0.116125 Worst:0.116125 Median:0.116125 Mean:0.116125 StdDev:0}
```

**Comment by corny** [comment]
Which version of Go are you using?
- https://www.reddit.com/r/golang/comments/63fnxx/timesince_sometimes_4975%C2%B5s_sometimes_0s/

**Comment by tenox7** [comment]
I'm using go1.12.1 (latest). Has the monotonic clock been implemented already?

**Comment by dmke** [comment]
This is most likely not a problem with monotonic/wall times, but a problem with the system clock resolution on windows, and how Go extracts the system time in `time.Now()`. The default clock resolution is 1/64s (15.6ms), so two consecutive calls to `time.Now()` should most likely yield the exact same time value.

The system clock resolution can be reduced (down to 0.5ms, I believe), but that has other performance implications, see here: https://randomascii.wordpress.com/2013/07/08/windows-timer-resolution-megawatts-wasted/. I don't know how we can raise the timer resolution from within in Go though (and, if at all possible, it should be opt-in anyway).

This is all from a theoretical point though, as we don't have Windows machines and expertise to debug and test this more thoroughly. If you ever find a way to achieve this, please let us know. I'd gladly merge code improving on this issue. For now, I'll close this issue as "wontfix" (read: "cantfix").
