### ISSUE TITLE
How to send "x" ping every "s" second? 

### ISSUE THREAD

**Issue by oijkn** [digineo/go-ping#13]
Hi,

Can you tell me how i can send 5 ping every 300 seconds for example, please? 

Thank you for your reply.

**Comment by dmke** [comment]
Just use [`Ping(destination, timeout)`](https://godoc.org/github.com/digineo/go-ping#Pinger.Ping) in a loop:

```go
dest, err := net.ResolveIPAddr("ip4", "localhost")
p, err := ping.New("0.0.0.0", "")
for {
    for i := 0; i < 5; i++ {
        rtt, err := p.Ping(target, 100 * time.Millisecond)
    }
    time.Sleep(300 * time.Second)
}
```
