### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by NinoM4ster** [digineo/go-ping#14]
There appears to be a memory leak somewhere in the program:

![leak](https://user-images.githubusercontent.com/8485761/90443601-e6405e00-e0b2-11ea-8665-eaabdf2c5bc3.gif)

I'm utilizing the included [ping-monitor](https://github.com/digineo/go-ping/tree/master/cmd/ping-monitor) code, without any modifications.

I'm running the script in a PowerShell terminal, with these arguments:
`go run . -pingInterval 1s -pingTimeout 1s -reportInterval 1s 8.8.8.8 10.10.10.10`

At first I thought the leak might have been in the summary printing, since I was running it on 1s intervals, but increasing it to 5s didn't seem to affect the memory leak rate. Though, decreasing the `-pingInterval` did change the leak rate noticeably.
(1MB of RAM filled up in 17 seconds with 50ms intervals, pinging the same 2 IPs)

**Comment by dmke** [comment]
This behavior is expected: The monitor needs to cache `reportInterval` / `pingInterval` × *number of IP addresses* data points to calculate values for mean and std deviation. Each data point is 8 byte for a `time.Duration` + 1 byte for a `bool` (what a waste :roll_eyes:). Add a bunch of overhead for each open socket, and I'm surprised it does not use more memory...

On Linux, it plateaus at 1.5 MB residual space (RSS), but concurrently only 8KB is used. Most of the memory is allocated for the raw socket connection.

I can't verify this on a Windows machine, though... How much memory do you consume after 1min? After 2min? After 5min?

**Comment by NinoM4ster** [comment]
> I can't verify this on a Windows machine, though... How much memory do you consume after 1min? After 2min? After 5min?

I'll make more tests very soon, including Linux tests. 🙂

By the way, how are you measuring the memory usage on Linux? Can I just use htop? What metrics should I observe?
There's metrics like resident and shared memory which I don't really understand.. I'm guessing `M_SIZE` is the right one?

Thanks!

**Comment by dmke** [comment]
I've just used `top`, `htop` will wokr as well:

```console
$ top -E k -p $(pgrep ping-monitor)
```

Btw., what is the Go version you've used to build the `ping-monitor`?

**Comment by dmke** [comment]
> On Linux, it plateaus at 1.5 MB residual space (RSS), but concurrently only 8KB is used. Most of the memory is allocated for the raw socket connection.

I seem to have mixed up the colums (and units). Rerunning this yields around 8 MB VSS and 1.5 MB RSS.

**Comment by dmke** [comment]
Ugh, those memory metrics are really confusing, especially before the first caffeine injection :-)

So, to clarify:

- RSS = residual size. Active memory currently used in RAM.
- VSS = virtual size. Amount of memory available to a process, but not necessarily paged into RAM

So, if a process `malloc`s 1GB of memory, but only uses the first few bytes, VSZ would be around 1G, but RSS would only show a few KB (seems to depend on page size (usually 4KB) and memory fragmentation. Also, shared memory (libraries, IPC stuff) is accounted differently.

I've added this snippet to `main.go` (just before the interrupt handler at the end of `main()`) to print the memory usage + allocations (adapted from [here](https://golangcode.com/print-the-current-memory-usage/)):

```go
import "runtime"

// ...

main() {
	// ...

	go func() {
		var m runtime.MemStats
		var r syscall.Rusage
		for {
			runtime.ReadMemStats(&m)
			syscall.Getrusage(syscall.RUSAGE_SELF, &r)
			fmt.Printf("RSS=%dk  Alloc=%dk  TotalAlloc=%dk  Sys=%dk  NumGC=%d\n",
				r.Maxrss, m.Alloc/1024, m.TotalAlloc/1024, m.Sys/1024, m.NumGC)
			time.Sleep(time.Second)
		}
	}()

	// Handle SIGINT and SIGTERM.
	// ...
}
```

```console
$ go build main.go
$ sudo setcap cap_net_raw+eip ping-monitor
$ ./ping-monitor -pingInterval 50ms -pingTimeout 50ms 172.16.0.1 172.16.0.20
RSS=7228k  Alloc=242k  TotalAlloc=242k  Sys=69971k  NumGC=0
RSS=9276k  Alloc=297k  TotalAlloc=297k  Sys=70483k  NumGC=0
...
RSS=11664k  Alloc=2816k  TotalAlloc=2816k  Sys=72145k  NumGC=0
172.16.0.1: {PacketsSent:10 PacketsLost:0 Best:0.537741 Worst:0.723987 Median:0.597655 Mean:0.6115574 StdDev:0.059364114}
172.16.0.20: {PacketsSent:10 PacketsLost:0 Best:0.12511 Worst:0.213127 Median:0.1554575 Mean:0.1562292 StdDev:0.023745045}
RSS=11664k  Alloc=2860k  TotalAlloc=2860k  Sys=72145k  NumGC=0
... (after a few minutes) ...
...
RSS=16088k  Alloc=1669k  TotalAlloc=60425k  Sys=73041k  NumGC=16
```

This time, the process plateaus at 16MB (see [`runtime.MemStats`](https://pkg.go.dev/runtime#MemStats) for more details).

The next step would be to create a real memory profile ([`runtime/pprof`](https://pkg.go.dev/runtime/pprof)) and investigate further.

**Comment by NinoM4ster** [comment]
> Btw., what is the Go version you've used to build the `ping-monitor`?

I updated Go to the latest version yesterday.. I think I had v1.14.2 before, though I'm not 100% sure.. I can redo all the tests in the old version as well, if you think it's necessary.

Btw, I don't think I was using `go build`, but instead `go run`. I don't know if that affects memory allocation in some way but I can also test both.

**Comment by dmke** [comment]
> redo all the tests in the old version [v1.14.2]

I don't think that's necessary.

> I was [not] using go build, but instead go run

`go run` builds a temporary binary and executes it, there should be no difference (apart from the way how `go run` treats exit codes, which are not relevant here). You can run `go run -x main.go -help` to see the gory details.

**Comment by dmke** [comment]
FYI, in a VM, Go allocates about 12 MB from the OS, and Task Manager reports 5.8 MB:

![image](https://user-images.githubusercontent.com/327411/94019169-bec76a00-fdb1-11ea-9358-5f74f9022028.png)

**Comment by NinoM4ster** [comment]
I'm so sorry. even though I said I was gonna make more tests "very soon" I ended up forgetting about it completely... it has been a busy week..

I'll try to run the tests today..

**Comment by dmke** [comment]
Oh, don't worry too much.

I've spent some time analyzing the memory profile with pprof: As far as I can tell, no actual memory is leaking. 40% of allocations happen in this line:

https://github.com/digineo/go-ping/blob/8a04c67e7d6f7ec1656cd90f5fc63365410a90a2/request.go#L50

which is used in the hot path (created for every ICMP echo request).

<details><summary>Side note</summary>

Interestingly, when changing this to `make(chan struct{}, 1)` (i.e. a buffered channel), the overall memory usage goes down a bit. It's only a few KB (of 70MB VSZ), so I'm blaming GC/runtime noise for now though.

</details>

The ping result history doesn't really appear in the memory profile: The slice for the results is created once per target IP address and used as a ring buffer afterwards; it's memory is constantly reused.

The rest of the allocations are used in `x/net/icmp` to parse the response messages.

If you want to take a stab at pprof as well, this is the code I've used to generate profile files (again, insert before the SIGINT/SIGTERM handling):

<details><summary>Instructions</summary>

```go
import (
	"bufio"
	"runtime"
	"runtime/pprof"
)

main() {
	// ...

	go func() {
		reader := bufio.NewReader(os.Stdin)
		for i := 0; ; i++ {
			// hit enter to generate a mem-xyz.prof file
			reader.ReadString('\n')

			fname := fmt.Sprintf("mem-%02d.prof", i)
			f, err := os.Create(fname)
			if err != nil {
				panic(fmt.Errorf("could not create memory profile: %w", err))
			}

			runtime.GC() // get up-to-date statistics
			if err := pprof.WriteHeapProfile(f); err != nil {
				panic(fmt.Errorf("could not write memory profile: %w", err))
			}
			f.Close()
			fmt.Println("written memory profile to", fname)
		}
	}()

	// Handle SIGINT and SIGTERM
	// ...
}
```

Then compile/run the ping-monitor command, wait a minute or two, and hit enter (repeat, if desired).

You can inspect the `mem-000.prof` files for example with `go tool pprof -http localhost:2020 mem-000.prof`.

</details>

**Comment by NinoM4ster** [comment]
Good afternoon!

I made some tests on my Windows machine and it turns out I didn't run the program for long enough the first time, so I guess the GC never kicked in...
Also, the initial memory usage (up to about 15 minutes) grows up exponentially, and that's what made me believe there was a memory leak.

Initially I was gonna run the tests for about 15~20 minutes, but then the interesting stuff started happening so I extended the test to 30 minutes.

I even made a helpful graph, which shows everything:
![go-ping memory chart](https://user-images.githubusercontent.com/8485761/94372874-b9329280-00d7-11eb-8804-0b1db3f05e04.png)

(keep in mind that those values are from Window's Task Manager, Details tab)

I deeply apologize for thinking it was a memory leak. It was my fault for not running tests for long enough. xD

**Comment by dmke** [comment]
Thank you for the follow up!

> I deeply apologize for thinking it was a memory leak. It was my fault for not running tests for long enough. xD

There's nothing to apologize for. For me, this was an opportunity to delve deeper into pprof, so I'm one experience richer than before. :-)

**Comment by NinoM4ster** [comment]
> For me, this was an opportunity to delve deeper into pprof, so I'm one experience richer than before.

That's great to hear!  ;)
