### ISSUE TITLE
Help me please with this library

### ISSUE THREAD

**Issue by shkabatur** [digineo/go-ping#15]
I'm newbie in golang, help me please. How to convert functionality of this library to one simple function:
func ping(timeout time.Duration, attemts int) (rtts []int, err error)
No one library that i have found provide such simple interface like this.
And i want to be able run about 500 instances of this function concurrently to monitor my network. 

If anyone can help I would be very grateful :)

**Comment by dmke** [comment]
```go
func ping(timeout time.Duration, attemts int) (rtts []int, err error)
```

This signature has no target IP address.

I'd suggest studying how [the `pingnet` example](cmd/pingnet/main.go) works (it is capable of pinging hundreds or thousands of targets in parallel - if you've got the bandwidth ;-)), specifically what `pingnet 192.168.1.1/24` exactly does.

**Comment by shkabatur** [comment]
> I'd suggest studying how [the `pingnet` example](https://github.com/digineo/go-ping/blob/master/cmd/pingnet/main.go) works (it is capable of pinging hundreds or thousands of targets in parallel - if you've got the bandwidth ;-)), specifically what `pingnet 192.168.1.1/24` exactly does.

Thanks :)
