### ISSUE TITLE
Unable to bind: listen ip6:ipv6-icmp ::: socket: address family not supported by protocol

### ISSUE THREAD

**Issue by skyxx** [digineo/go-ping#16]
Hi,
When you have only one of IPv4 or IPv6 network interfaces ping fails

`Unable to bind: listen ip6:ipv6-icmp ::: socket: address family not supported by protocol`

So handling this situlation in **pinger.go** shoul be corrected.

Thanks.

**Comment by corny** [comment]
This works as intended. If you don't have IPv6 connectivity, leave the IPv6 bind address empty:
```golang
pinger, err := New("0.0.0.0", "")
```
