### ISSUE TITLE
feature request: obtain source address of ICMP reply packet

### ISSUE THREAD

**Issue by stapelberg** [digineo/go-ping#4]
When doing a broadcast/multicast ping (e.g. to `ip6-allrouters`, i.e. `ff02::2`), I’m interested in the source address of the ICMP reply packet.

Unfortunately, this package does not offer a way to obtain the source address AFAICT. Could a way be added? If you lack the time, I’m happy to contribute a PR, but figured I’d check with you first regarding the preferred API for the feature, provided you’re okay with accepting it.

Thanks in advance!

**Comment by corny** [comment]
Such a function requires to specify a duration to wait for the packets. I will try to implement it next week.
