### ISSUE TITLE
Large number of hosts unstable results

### ISSUE THREAD

**Issue by lbrictson** [digineo/go-ping#6]
I'm adding 300+ hosts to a monitor instance with a ping interval of 60s, report interval 120s, and timeout of 4.  The results indicate lost packets for IPs that are indeed up, etc.  

After adding some error messages it looks like it is timeout i/o error.  Are there any suggestions for pinging >100 addresses?

**Comment by corny** [comment]
Please use tcpdump or wireshark to verify that all hosts do really reply.
